daiquiri/metadata/models.py
daiquiri/metadata/serializers/__init__.py
daiquiri/metadata/serializers/datacite.py

We have been adding `related_identfiers` metadata-entry for Tables and Schemas in order to fill the field in the `DataciteSerializer` for the oai interface. 
1. Added `related_identifiers` as a column in the tables and schemas metadata
2. Added `related_identifiers` in `DataciteSchemaSerializer`
3. Use the `JSONListField` of `daiquiri.core.serializers` to implicitly call `get_related_identifiers` (built-in rest_framework)

WIP: 76 add related identifier entry in metadata

---

daiquiri/datalink/adapter.py
daiquiri/oai/adapter.py

This PR fixes two problems:
* Daiquiri used to crash if a schema/table has `relatedIdentifiers`, but the `related_identifier` value is `null` or missing.
* Related identifiers were ignored for the creation of the DataCite record for OAI, since the (empty) search in the datalink tables overwrite the information in the metadata store.

Fix datalink adapter

---

daiquiri/metadata/templates/metadata/table.html

From now on, the column description containing html code is rendered correctly in the table overview of the metadata.
`default_if_none:''` is omitted since the new definition requires column.description to be a string, e.g. `""`

fix html/md render of the column description in the metadata

---

daiquiri/core/settings/django.py
daiquiri/files/utils.py
daiquiri/query/viewsets.py
requirements.txt

The django sendfile module is not compatible to django4 we therefore switched to sendfile2

Sendfile debug

---

requirements.txt

Antlr is a dependancy of queryparser not daiquiri.

removed the antlr requirement from daiquiri

---

daiquiri/core/utils.py

The queues such as 
```python 
{
'key': '5h',
'label': '5 Hours',
'timeout': 18000,
'priority': 1,
'access_level': 'INTERNAL',
'groups': []
},
```
were not filtered out for the not authenticated users. 
With the proposed fix, the filter works correctly.

fix filter for the access_level INTERNAL

---

daiquiri/metadata/admin.py
daiquiri/query/admin.py

Problem: the search for some models (e.g., `DownloadJobs`) in Django Admin didn't work (internal server error).
Bug: the search fields didn't match the fields of the corresponding model. In some models `__str__` was used as a search field which doesn't seem to work.
Fix: changed the `search_field` accordingly to match the corresponding model

fix search fields for djago admin

---

daiquiri/core/generators.py

now the existence of the ucd key is checked (not guarantied).

fixed the missing ucd issue

---

daiquiri/auth/templates/socialaccount/login.html

Currently, daiquiri uses the standard template from django-allauth, which doesn't  use the styling of the website. For instance, see https://gaia.aip.de/accounts/google/login/?process=login. 
This PR adds a simple login template for the redirection  to the third party websites, which uses the styling of the website.

add the missing template for the login via socialaccount

---

daiquiri/core/adapter/database/base.py
daiquiri/core/adapter/database/postgres.py

added missing compatible types between VOTable and Postgres and raised an error in case an unsupported type is provided

BUG: valid unicodeChar column type is not supported

---

daiquiri/metadata/static/metadata/js/metadata.js
daiquiri/metadata/templates/metadata/management_modal_form_schemas_contributors.html
daiquiri/metadata/templates/metadata/management_modal_form_schemas_creators.html
daiquiri/metadata/templates/metadata/management_modal_form_tables_contributors.html
daiquiri/metadata/templates/metadata/management_modal_form_tables_creators.html

The input form for affiliations is removed from the metadata management to ensure the compatibility with REST API Currently, affiliations are stored in a list of dictionaries while the frontend expects a list of strings.

remove affiliations from the frontend

---

daiquiri/core/renderers/datacite.py

The ROR identifier is added to the OAI metadata renderer which is very useful for the creators/collaborators that are organizations.

add ror id to the datacite metadata

---

daiquiri/datalink/adapter.py
daiquiri/datalink/viewsets.py
daiquiri/oai/adapter.py
daiquiri/query/models.py
daiquiri/query/utils.py

making use of tables for datalink is useful since it allows more flexibility (for non-programmable entries) and it is easier to maintain.
Additionally the datalink entries are usually part of the release, and as such get a DOI. 
However, in one cases making use of tables to provide datalink entries may not be confortable:
* in case of too many entries: like in Gaia, several datalink entries per source_id (same for applause...)
In these cases datalink entries generated on the fly based on the ID are necessary.
I added a DynamicDatalinkAdapterMixin class that take care of the dynamic datalink entries. I also added a method called: `get_datalink_rows` and `get_dyn_datalink_links` to the `BaseDatalinkAdapter`, to provide a single point of gathering for the datalink entries (slighlty slower). …

Dynamic datalink

---

daiquiri/files/utils.py

Remove hard coded dependency on stats from the files app

---

daiquiri/metadata/assets/js/components/Management.js
daiquiri/metadata/assets/js/components/Schemas.js
daiquiri/metadata/models.py

This PR fixes two issues
- the list of schemas and tables in the DB browser do not update after click on the column anymore. Also, the list of schemas is not updated after the click on a table.
- The list of tables/columns now always start at the top of the list if the list is updated by clicking new schema/table.

Fix db browser

---

daiquiri/auth/templates/account/account_profile.html
daiquiri/contact/templates/contact/contact.html
daiquiri/core/adapter/database/mysql.py
daiquiri/core/assets/js/components/table/Table.js
daiquiri/core/assets/js/components/table/TableCell.js
daiquiri/core/assets/js/components/table/TableModalDatalinks.js
daiquiri/core/assets/js/utils/table.js
daiquiri/core/assets/scss/base.scss
daiquiri/core/assets/scss/base/codehilite.scss
daiquiri/core/assets/scss/base/layout.scss
daiquiri/core/assets/scss/base/modal.scss
daiquiri/metadata/templates/metadata/schema.html
daiquiri/metadata/templates/metadata/schemas.html
pyproject.toml

This PR adds following changes:
- minor changes in styling, e.g., styling of the table in the metadata of a schema
- a number of minor fixes, like fix of an mysql adapter ( it fixed also the ci tests)  or rendering of the filepath in the results table
- added codehilite for the rendering of the code in the markdown files
- Major overhaul of the datalink modal. I simplified it quiet a bit for the user.  We will provide links only for the previews (if exist), downloadable files (if exist) and all image previes with the semantic `#preview-image` or `#preview-plot`. If the user wants something else then there will be a link that leads to the full datalink viewer.
So...now it looks something like this

Minor fixes of styling, add codehilite, change datalink modal

---

daiquiri/__main__.py
daiquiri/core/management/commands/build.py
daiquiri/core/management/commands/clean.py
daiquiri/core/management/commands/npm.py
daiquiri/core/management/settings.py
daiquiri/core/settings/django.py
pyproject.toml

This PR ports some functionality I developed for RDMO last year over to Daiquiri. I adds an `daiquiri-admin` executable that can be used in any directory. Right now, I can be used for 3 things:
```
daiquiri-admin npm run [watch|build|build:prod]  # shortcut for nvm use and npm run ...
daiquiri-admin build  # build the front-end and then the python package
daiquiri-admin clean [all|dist|media|npm|python|static]  # removes files which are gitignored
```

Add daiquiri-admin and scripts for npm, build, clean

---

daiquiri/files/templates/files/list-results.html
daiquiri/files/templates/files/search-input.html
daiquiri/files/templates/files/search-results.html

The styling of the search results page was forgotten during the update of the front-end. This PR fixes it.

Fix styling of the cms search results

---

daiquiri/core/adapter/database/base.py
daiquiri/core/assets/js/components/form/Select.js
daiquiri/core/assets/js/components/table/TableCell.js
daiquiri/core/assets/js/components/table/TableModalDatalinks.js
daiquiri/core/assets/scss/base/navigation.scss
daiquiri/core/utils.py
daiquiri/query/assets/js/api/QueryApi.js
daiquiri/query/assets/js/components/submit/job/JobDownload.js
daiquiri/query/assets/js/components/submit/job/downloads/FormDownload.js
daiquiri/query/assets/js/hooks/queries.js
daiquiri/query/tasks.py
daiquiri/query/validators.py
daiquiri/query/viewsets.py

Closes #267
Now, the custom download services can supply forms by defining a function `get_form(self, query_job)` in their model. 
For example
```py
def get_form(self, query_job):
if query_job.nrows > settings.CUSTOM_DOWNLOAD_MAX_ROWS:
return {
'label': settings.CUSTOM_DOWNLOAD_FORM['label'],
'description':  f'The service is available only for query results that contain a maximum of {settings.CUSTOM_DOWNLOAD_MAX_ROWS:} rows.'
}
else:
return settings.CUSTOM_DOWNLOAD_FORM
```
Basically, one can add any kind of complex conditions into the function and provide custom messages/description for every case. The description will be rendered on the webpage.
If the conditional form is not required then there is no need to define `get_form`. Add the form directly to the settings `QUERY_DOWNLOADS` and …

267 fix download forms

---

daiquiri/core/assets/js/components/table/TableCell.js
daiquiri/core/assets/js/components/table/TableModal.js
daiquiri/core/assets/js/components/table/TableModalDatalinks.js
daiquiri/core/assets/js/utils/table.js
daiquiri/query/assets/js/components/submit/forms/dropdowns/SimbadDropdown.js
daiquiri/query/assets/js/components/submit/forms/dropdowns/VizierDropdown.js
daiquiri/query/urls.py

This PR does the following
- The link to the note modal is now using the basename instead of the full path to the file
- The modals have a download button for images and notes. Otherwise it was not obvious how to download them.
- The url path to the query app allows single trailing slash.
- Minor styling changes and some code refactoring.

Fix rendering of links for modals

---

daiquiri/core/adapter/database/postgres.py
daiquiri/core/renderers/vosi.py
daiquiri/jobs/renderers.py
daiquiri/jobs/settings.py
daiquiri/jobs/utils.py
daiquiri/jobs/viewsets.py
daiquiri/query/assets/js/components/submit/forms/FormSql.js
daiquiri/query/assets/js/components/submit/job/JobParameters.js
daiquiri/query/models.py
daiquiri/query/serializers.py
daiquiri/query/viewsets.py
daiquiri/tap/vo.py
testing/config/settings/__init__.py

This PR adds a limit on the number of rows that can be retrieved in a single query. It's a standard in all TAP services. This will prevent users to download de facto unlimited data. 
For now, the default limit is set to 5 million rows. If the limit is reached the correct 'OVERFLOW' flag is set in the VO resources and it's also indicated in the query information card on the web interface.

Add a limit (maxrec) on rows for all jobs

---

daiquiri/core/assets/js/components/table/TableCell.js
daiquiri/core/assets/js/utils/table.js
daiquiri/query/assets/js/components/submit/job/JobResults.js
daiquiri/serve/assets/js/hooks/params.js
daiquiri/serve/views.py

Currently, the resolver in the `serve` app can handle only two arguments `key` and `value`. The reference url created in the results table (case `meta.ref`) is of the form `/serve/reference/<column_name>/<value>`. 
This PR adds `job_id` as a parameters to the reference url `/serve/reference/<column_name>/<value>?job_id=<job_id>`. The job_id is provided only if it's present. For example, the reference URLs created in `/serve/table/<schema_name>/<table_name>` won't have the `job_id`. 
The job_id can provide some context to the resolver if needed. For example, one can implement a custom results viewer tailored to the project. Also, it can be handy to have the full list of objects in the viewer to make it possible to quickly click through them.

Add job_id to the reference url

---

daiquiri/files/utils.py
daiquiri/files/views.py

This PR allows downloading files using API token. 
Previously, `wget` and `curl` worked only with the publicly available files. If the access level for the directory was set to 'INTERNAL' or 'PRIVATE' then the download was not possible because the request was always redirected to the login page. 
Here, I'm using the `TokenAuthentication` class from the DRF in order to authenticate the user. 
I tested the implementation with curl and wget
```bash
wget --header 'Authorization: Token <token>'  <url_to_the_file>
curl -H 'Authorization: Token <token>'  <url_to_the_file>
```

Add token authentication for file download
