django-daiquiri/daiquiri

daiquiri_contact/views.py
Anonymous with no email exception: fixed.
=> anonymous user with no email fixed

daiquiri_contact/static/contact/js/messages.js, daiquiri_contact/templates/contact/messages.html, daiquiri_contact/templates/contact/messages_options.html, daiquiri_contact/views.py
=> Contact facelift

daiquiri/core/settings/base.py, daiquiri/core/utils.py, daiquiri/meetings/forms.py
* Allow to set participant.accepted=True by default
* Allow to set EMAIL_REPLY_TO via settings
=> Meetings adjustments

daiquiri/core/adapter/database/mariadb.py, daiquiri/core/adapter/database/mysql.py, daiquiri/core/adapter/database/postgres.py, daiquiri/core/adapter/download/base.py, daiquiri/core/generators.py, daiquiri/core/settings/daiquiri.py, daiquiri/jobs/exceptions.py, daiquiri/jobs/models.py, daiquiri/jobs/viewsets.py, daiquiri/query/models.py, daiquiri/query/process.py, daiquiri/query/tasks.py, daiquiri/query/utils.py
=> Refactor sync query jobs

daiquiri/core/settings/logging.py, daiquiri/jobs/tests/mixins.py, daiquiri/jobs/utils.py, daiquiri/jobs/viewsets.py, daiquiri/query/models.py, daiquiri/query/process.py, daiquiri/query/utils.py
* Allow GET for Sync Jobs
* Add query log
* Cleanup
=> Refactor sync (part 2)

daiquiri/metadata/templates/metadata/table.html
table numbers info on metadata page
=> nrows,ncols added

CONTRIBUTING.rst, README.md, daiquiri/tap/utils.py, testing/sql/mysql/data.sql
This should be sufficient.
Updating the name at this place will catch the signals when `updating metadata` and calling `rebuild_tap_schema`.
=> WIP: made the name of tap_schema.tables unique by fully qualifying them.

CONTRIBUTING.rst, README.md, daiquiri/query/models.py, testing/sql/mysql/data.sql
added the missing xml element: executionDuration in the Query model, when uploaded via Web interface, preventing archiving via TAP interface.
=> WIP: missing element in OAI output

daiquiri/core/static/core/css/codehilite.scss, daiquiri/core/templates/core/base_head.html, daiquiri/core/utils.py, requirements.txt
added highlights for code in CMS.
=> Md codehilite

daiquiri/core/generators.py
This PR should fix the `DALFormatError: ValueError: 79:50: not well-formed (invalid token)` with gaia.aip.de.
=> Add additional escaping in generate_votable

daiquiri/core/adapter/database/postgres.py, daiquiri/core/settings/django.py
added the tablespace option for user queryjob tables, settable via env variable
=> FEATURE: Tablespace option

daiquiri/query/static/query/js/services/plot.js
The fix changes the width of the plotting window from  a constant value to the dynamic width of `col-md-9`.
=> fix the width of the plot window

daiquiri/core/utils.py
=> fix user access to the private items

daiquiri/query/templates/query/query_form_upload.html, daiquiri/query/viewsets.py
=> add info on max upload size in the query interface

daiquiri/contact/forms.py, daiquiri/contact/templates/contact/contact.html, daiquiri/contact/tests/test_views.py, daiquiri/contact/views.py
=> remove email and username from the form

daiquiri/datalink/templates/datalink/datalink.html
improve the datalink viewer:
* less technical (hide non-necessary datalink columns)
* human readable file size
=> improved the default datalink viewer

daiquiri/query/utils.py
Added arraysize attribute after parsing the input VOTable for upload. Information is now available and can be used.
=> Keeping metdata of UPLOAD table

daiquiri/core/adapter/database/base.py
added the char(*) catch for upload
=> BUG: upload fails with Char(*) type

daiquiri/core/adapter/database/postgres.py
Added a DATATYPE spoint to properly treat download of spoint as char(*)
=> BUG: spoint are unproperly downloaded

daiquiri/datalink/adapter.py, daiquiri/metadata/serializers/datacite.py, daiquiri/oai/adapter.py
=> 176 add detached header datalink semantic to the oai adapter

daiquiri/query/validators.py
=> Add table name validator

daiquiri/core/settings/django.py, daiquiri/core/static/core/html/browser.html, daiquiri/query/static/query/js/apps/query.js, daiquiri/query/static/query/js/services/query.js, daiquiri/query/viewsets.py
=> remove user schema from the column search

daiquiri/registry/templates/registry/root.html
=> add link for the oai sets to the registry page

daiquiri/files/views.py
=> fix the bug for the  rendering of .html with layout

daiquiri/core/templates/core/partials/table_tooltip.html
=> fix html rendering of the column description

daiquiri/core/renderers/__init__.py
=> Fix xml rendering of values that equal to zero

daiquiri/core/adapter/database/postgres.py
=> Fix for psycopg3

daiquiri/core/adapter/database/base.py, daiquiri/core/adapter/database/postgres.py
=> Fix parsing of arrays for upload

daiquiri/core/adapter/database/postgres.py, daiquiri/core/generators.py
Closes #194 with a rebased version
=> Fix metadata discovery for the array columns

daiquiri/query/assets/js/components/submit/forms/Form.js
Allow dropbdown forms when adding custom query
=> Dropdown forms

daiquiri/core/assets/scss/base.scss, daiquiri/core/assets/scss/base/progress.scss, daiquiri/jobs/managers.py, daiquiri/query/assets/js/components/submit/Status.js
This PR adds progress bar for the quota in the status card.
=> Add progress bar to the status card

daiquiri/core/assets/js/components/form/Select.js, daiquiri/core/assets/js/components/form/SubSelect.js, daiquiri/query/assets/js/components/submit/forms/Form.js, daiquiri/query/assets/js/components/submit/forms/FormSql.js
Add a new form `SubSelect` that opens a second selection menu for each dropdown menu item.
=> Feature subselect form

.ruff.toml, daiquiri/core/adapter/database/base.py, daiquiri/core/adapter/database/postgres.py, daiquiri/core/adapter/download/base.py, daiquiri/core/generators.py, daiquiri/query/assets/js/components/submit/job/JobOverview.js, daiquiri/query/settings.py, daiquiri/query/tasks.py, daiquiri/query/utils.py, daiquiri/query/viewsets.py, pyproject.toml
This adds the option to download files as `parquet`
=> Feature parquet

daiquiri/query/process.py, pyproject.toml
=> 283 fix metadata for user tables
